#### NUMPY - Numerical Python


In [238]:
import numpy as np


In [239]:
l = [1, 2, 3, 4]


In [240]:
ar = np.array(l)


In [241]:
ar


array([1, 2, 3, 4])

In [242]:
# n-dimensional array
type(ar)


numpy.ndarray

In [243]:
np.array([
    [1, 2],
    [3, 4]
])


array([[1, 2],
       [3, 4]])

In [244]:
# or

np.asarray(l)


array([1, 2, 3, 4])

In [245]:
a = [1, 2, 3]


In [246]:
np.asanyarray(a)  # converts to some array


array([1, 2, 3])

In [247]:
b = np.matrix(l)


In [248]:
b


matrix([[1, 2, 3, 4]])

In [249]:
a = np.array(l)


In [250]:
# swallow copy - both point to the same location
c = a


In [251]:
c


array([1, 2, 3, 4])

In [252]:
a


array([1, 2, 3, 4])

In [253]:
c[0] = 100


In [254]:
c


array([100,   2,   3,   4])

In [255]:
a


array([100,   2,   3,   4])

In [256]:
# copy
d = np.copy(a)
d


array([100,   2,   3,   4])

In [257]:
d[0] = 89


In [258]:
a


array([100,   2,   3,   4])

In [259]:
d


array([89,  2,  3,  4])

In [260]:
np.fromfunction(lambda i, j: i == j, (3, 3))


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [261]:
np.fromfunction(lambda i, j: i * j, (3, 3))


array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [262]:
iter = (i*i for i in range(5))


In [263]:
np.fromiter(iter, float)


array([ 0.,  1.,  4.,  9., 16.])

In [264]:
# From delimiter

np.fromstring('234 234', sep=" ")


array([234., 234.])

In [265]:
np.fromstring('2,3', sep=",")


array([2., 3.])

## Numpy Datatypes


In [266]:
l = [1, 2, 3, 4, 5, 6]


In [267]:
ar = np.array(l)


In [268]:
ar


array([1, 2, 3, 4, 5, 6])

In [269]:
# Dimension of the array
ar.ndim


1

In [270]:
ar2 = np.array([[1, 2, 3, 4], [2, 5, 7, 8]])


In [271]:
ar2


array([[1, 2, 3, 4],
       [2, 5, 7, 8]])

In [272]:
ar2.ndim


2

#### No of elements in the array


In [273]:
ar2.size


8

In [274]:
ar.size


6

#### Shape of the array/matrix


In [275]:
ar.shape


(6,)

In [276]:
ar2.shape


(2, 4)

#### Datatype


In [277]:
ar.dtype


dtype('int64')

In [278]:
ar3 = np.array([(1.4, 45, 45), (23, 45, 66)])


In [279]:
ar3


array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [280]:
ar3.dtype


dtype('float64')

#### Producing Arrays


In [281]:
# Can't produce float values
list(range(5))


[0, 1, 2, 3, 4]

In [282]:
# Producing floating point numbers
np.arange(2.3, 5.6)


array([2.3, 3.3, 4.3, 5.3])

In [283]:
# With jump
list(np.arange(2.3, 5.6, .3))


[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [284]:
# Provides 10 equidistant numbers
np.linspace(1, 5, 10)


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#### produces array/matrix with value 0


In [285]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [286]:
np.zeros((3, 4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [287]:
# 3 matrixes of 4x2 matrix
np.zeros((3, 4, 2))


array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [288]:
np.ones(4)


array([1., 1., 1., 1.])

In [289]:
np.ones((4, 6))


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [290]:
np.ones((4, 6))+5


array([[6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.]])

#### Generating empty arrays


In [291]:
np.empty((5, 4))


array([[0.91422498, 1.78076479, 0.44352956, 0.05237718],
       [1.8906902 , 0.24159543, 1.51250674, 1.67098182],
       [1.30403438, 1.84578515, 0.20567122, 1.3471049 ],
       [0.24581259, 0.92446268, 1.3552593 , 0.20636444],
       [1.04895111, 1.98511181, 1.03252809, 0.79384269]])

#### Identity matrix

- Square Matrix
- det = 1
- Diagonal values - 1


In [292]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [293]:
np.linspace(2, 4, 20)


array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

#### Logrithmic data between two points


In [294]:
# default base = 10

np.logspace(2, 5, 10)


array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [295]:
# Log base 2
np.logspace(2, 5, 10, base=2)


array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

#### random function


In [296]:
# Standard normal distribution
# Return a sample (or samples) from the "standard normal" distribution.
# mean = 0
# SD = 1
arr1 = np.random.randn(4, 5)
arr1


array([[ 0.62051605, -1.2864136 , -0.40023397, -1.00766361, -1.32874889],
       [ 0.18827569, -0.45706264,  0.51235004,  0.66787796,  0.88205075],
       [-0.26824799, -0.97007592, -0.91010019,  2.30117325,  1.12487421],
       [-2.48083369,  0.925221  , -0.08506019,  1.47373909, -0.42276037]])

#### random function array/matrix to dataframe


In [297]:
import pandas as pd


In [298]:
pd.DataFrame(arr1)


0         1         2         3         4
0  0.620516 -1.286414 -0.400234 -1.007664 -1.328749
1  0.188276 -0.457063  0.512350  0.667878  0.882051
2 -0.268248 -0.970076 -0.910100  2.301173  1.124874
3 -2.480834  0.925221 -0.085060  1.473739 -0.422760

In [299]:
np.random.rand(3, 5)


array([[0.70098969, 0.18636593, 0.50201011, 0.79471167, 0.08461973],
       [0.45041403, 0.33268255, 0.17038769, 0.24126536, 0.2800343 ],
       [0.74142995, 0.76828317, 0.16294341, 0.45647675, 0.65808245]])

In [300]:
# Generate random number in an interval
np.random.randint(4, 10)


5

In [301]:
# A matrix of 3x4 data
np.random.randint(4, 10, (3, 4))


array([[6, 7, 9, 8],
       [9, 8, 4, 5],
       [7, 8, 5, 6]])

In [302]:
pd.DataFrame(np.random.randint(1, 100, (2000, 300))
             ).to_csv("test.csv", index=None)
pd.read_csv("test.csv")


0   1   2   3   4   5   6   7   8   9  ...  290  291  292  293  294  \
0     10  28  33  21  78  26  60  89  65  84  ...   66   34   61   79   78   
1     19  96  22  53  22   2  84  17  20   3  ...   39   54   43   79   45   
2     53  80  30  14  67  89   1  90  28  66  ...   71   95   23   64   25   
3     24  71  21  95  19  13  62  50  59  17  ...   58   90   76   77    5   
4     41   5  18  88  90  54  23  94  76  64  ...   76   41   28   42   79   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
1995  89  44  84  39  10  55   8   3  91  81  ...   25    3   43   92   84   
1996  15  63  80  72  16  86  44   7  75  64  ...   28   42   94   88   89   
1997  11  11  53  75  22  71  20  61  80  80  ...   97   22   59   29   91   
1998  45  21  70  61  10  56  24  99  46  17  ...   73    1   93   82   56   
1999  43  77  43  31  57  69  65  86   8  37  ...   77   25   35   69   69   

      295  296  297  298  299  
0      77   84   61   63    2  
1      55   74   19   86   88  
2      56   17   38   87   68  
3      21   15   94   40   60  
4      41   43   40   77   51  
...   ...  ...  ...  ...  ...  
1995   95   32   24   41   82  
1996   31   93   39   95   56  
1997   26   51   27    7   32  
1998   14   40   80   51   82  
1999    1   93   40   41   60  

[2000 rows x 300 columns]

#### Reshaping the matrix data


In [303]:
arr1


array([[ 0.62051605, -1.2864136 , -0.40023397, -1.00766361, -1.32874889],
       [ 0.18827569, -0.45706264,  0.51235004,  0.66787796,  0.88205075],
       [-0.26824799, -0.97007592, -0.91010019,  2.30117325,  1.12487421],
       [-2.48083369,  0.925221  , -0.08506019,  1.47373909, -0.42276037]])

In [304]:
# Original matrix = 4*5 = 20 elements
# Reshaped matrix  = 5*4 = 20 elements
arr1.reshape(5, 4)


array([[ 0.62051605, -1.2864136 , -0.40023397, -1.00766361],
       [-1.32874889,  0.18827569, -0.45706264,  0.51235004],
       [ 0.66787796,  0.88205075, -0.26824799, -0.97007592],
       [-0.91010019,  2.30117325,  1.12487421, -2.48083369],
       [ 0.925221  , -0.08506019,  1.47373909, -0.42276037]])

In [305]:
# '-' will take the required 2nd parameters for the reshaping based on the first paremater
arr2 = arr1.reshape(10, -1)
arr2


array([[ 0.62051605, -1.2864136 ],
       [-0.40023397, -1.00766361],
       [-1.32874889,  0.18827569],
       [-0.45706264,  0.51235004],
       [ 0.66787796,  0.88205075],
       [-0.26824799, -0.97007592],
       [-0.91010019,  2.30117325],
       [ 1.12487421, -2.48083369],
       [ 0.925221  , -0.08506019],
       [ 1.47373909, -0.42276037]])

In [306]:
# Extracting data from an array
arr2[1][1]


-1.0076636107926602

In [307]:
arr2[2:5, 1]


array([0.18827569, 0.51235004, 0.88205075])

In [308]:
arr3 = np.random.randint(1,100,(5,6))
arr3

array([[22, 42, 99, 38,  7, 30],
       [60, 15, 14, 58, 70, 79],
       [71,  1, 81, 77, 89, 85],
       [ 8, 34, 84, 48, 99, 89],
       [13, 53, 94, 74, 49, 96]])

In [309]:
# Find all data values > 50
arr3[arr3 > 50]


array([99, 60, 58, 70, 79, 71, 81, 77, 89, 85, 84, 99, 89, 53, 94, 74, 96])

In [310]:
arr3[2:4, 1:3]

array([[ 1, 81],
       [34, 84]])

In [311]:
# Re-assignment is possible
arr3[0][0] = 500


In [312]:
arr3

array([[500,  42,  99,  38,   7,  30],
       [ 60,  15,  14,  58,  70,  79],
       [ 71,   1,  81,  77,  89,  85],
       [  8,  34,  84,  48,  99,  89],
       [ 13,  53,  94,  74,  49,  96]])

#### matrix arithmetic

In [313]:
arr4 = np.random.randint(1, 3, (3, 3))
arr5 = np.random.randint(1, 3, (3, 3))

In [314]:
arr4

array([[1, 1, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [315]:
arr5

array([[2, 1, 1],
       [2, 2, 2],
       [1, 1, 1]])

In [316]:
arr4+arr5

array([[3, 2, 2],
       [3, 4, 3],
       [3, 2, 3]])

In [317]:
arr4*arr5

array([[2, 1, 1],
       [2, 4, 2],
       [2, 1, 2]])

In [318]:
arr4-arr5

array([[-1,  0,  0],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [319]:
arr4/arr5


array([[0.5, 1. , 1. ],
       [0.5, 1. , 0.5],
       [2. , 1. , 2. ]])

#### Matrix Multiplication

In [320]:
arr4@arr5

array([[5, 4, 4],
       [7, 6, 6],
       [8, 6, 6]])

## Numpy Broadcasting

In [321]:
arr6= np.zeros((4,4))
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [322]:
row = np.array([1,2,3,4])
row

array([1, 2, 3, 4])

In [323]:
arr6 + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [324]:
row.ndim


1

In [325]:
row.shape

(4,)

In [326]:
col = np.array([[1,2,3,4]])
col

array([[1, 2, 3, 4]])

In [327]:
col.shape


(1, 4)

In [328]:
col.ndim

2

#### Transpose of the matrix

In [329]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [330]:
col.T + arr6

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [331]:
col

array([[1, 2, 3, 4]])

In [332]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [333]:
arr7 = np.random.randint(1,4,(3,4))

#### squareroot of an array/matrix

In [334]:
np.sqrt(arr7)

array([[1.        , 1.73205081, 1.41421356, 1.        ],
       [1.        , 1.73205081, 1.        , 1.        ],
       [1.73205081, 1.73205081, 1.73205081, 1.41421356]])

#### Exponent of an array/matrix

In [336]:
np.exp(arr7)

array([[ 2.71828183, 20.08553692,  7.3890561 ,  2.71828183],
       [ 2.71828183, 20.08553692,  2.71828183,  2.71828183],
       [20.08553692, 20.08553692, 20.08553692,  7.3890561 ]])

#### Log of array/matrix

In [338]:
np.log10(arr7)

array([[0.        , 0.47712125, 0.30103   , 0.        ],
       [0.        , 0.47712125, 0.        , 0.        ],
       [0.47712125, 0.47712125, 0.47712125, 0.30103   ]])