## Array Manipulation

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[9, 7, 5, 4],
       [2, 3, 7, 1],
       [9, 5, 9, 6]])

In [4]:
arr.reshape(6,2)

array([[9, 7],
       [5, 4],
       [2, 3],
       [7, 1],
       [9, 5],
       [9, 6]])

In [5]:
arr.reshape(2, -45)

array([[9, 7, 5, 4, 2, 3],
       [7, 1, 9, 5, 9, 6]])

#### Transpose

In [6]:
arr.T

array([[9, 2, 9],
       [7, 3, 5],
       [5, 7, 9],
       [4, 1, 6]])

#### Change any matrix to 1D-array

In [7]:
arr.flatten()

array([9, 7, 5, 4, 2, 3, 7, 1, 9, 5, 9, 6])

In [8]:
arr1 = np.array([1, 2, 3, 4])


In [9]:
arr1.ndim

1

#### Change dimension by +1 columnwise

In [10]:
np.expand_dims(arr1, axis=1)


array([[1],
       [2],
       [3],
       [4]])

#### Change dimension by +1 row-wise

In [11]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 4]])

#### Change dimension to 1D if only 1 element is present en each row.

In [12]:
data = np.array([[1], [2], [3]])
data

array([[1],
       [2],
       [3]])

In [13]:
np.squeeze(data)

array([1, 2, 3])

In [14]:
arr1

array([1, 2, 3, 4])

#### Repeating the element of a list.

In [15]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

#### Shifting elements of an array

In [16]:
# Shift element by 2
np.roll(arr1, 2)

array([3, 4, 1, 2])

#### putting all array elements on the diagonal of a matrix with every other elemnt as '0'.

In [17]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Numpy - Basic Arithmetic Operations

In [18]:
arr1 = np.random.randint(1,10 , (3,4))

In [19]:
arr2 = np.random.randint(1,10 , (3,4))

In [20]:
arr1

array([[9, 2, 2, 4],
       [2, 3, 1, 5],
       [1, 5, 4, 3]])

In [21]:
arr2

array([[9, 4, 8, 1],
       [7, 4, 2, 2],
       [8, 8, 4, 4]])

#### Addition

In [22]:
arr1+arr2

array([[18,  6, 10,  5],
       [ 9,  7,  3,  7],
       [ 9, 13,  8,  7]])

#### Multiplication

In [23]:
arr1*arr2

array([[81,  8, 16,  4],
       [14, 12,  2, 10],
       [ 8, 40, 16, 12]])

#### Division

In [24]:
arr1/arr2

array([[1.        , 0.5       , 0.25      , 4.        ],
       [0.28571429, 0.75      , 0.5       , 2.5       ],
       [0.125     , 0.625     , 1.        , 0.75      ]])

#### Subtraction

In [25]:
arr1-arr2

array([[ 0, -2, -6,  3],
       [-5, -1, -1,  3],
       [-7, -3,  0, -1]])

#### Mod/Remainder

In [26]:
arr1 % arr2


array([[0, 2, 2, 0],
       [2, 3, 1, 1],
       [1, 5, 0, 3]])

#### Power

In [27]:
arr1 ** arr2


array([[387420489,        16,       256,         4],
       [      128,        81,         1,        25],
       [        1,    390625,       256,        81]])

## Bitwise Operation

#### Bitwise AND

In [28]:
arr1&arr2

array([[9, 0, 0, 0],
       [2, 0, 0, 0],
       [0, 0, 4, 0]])

#### Bitwise OR

In [29]:
arr1 | arr2

array([[ 9,  6, 10,  5],
       [ 7,  7,  3,  7],
       [ 9, 13,  4,  7]])

#### Negation

In [30]:
~arr1

array([[-10,  -3,  -3,  -5],
       [ -3,  -4,  -2,  -6],
       [ -2,  -6,  -5,  -4]])

#### bool(Greater than?)

In [31]:
arr1>arr2

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False, False]])

#### Numpy - String Functions

In [32]:
arr = np.array(["Aditya", "Azad"])

In [33]:
arr

array(['Aditya', 'Azad'], dtype='<U6')

#### Making all characters uppercase

In [34]:
np.char.upper(arr)

array(['ADITYA', 'AZAD'], dtype='<U6')

#### Making all characters title-case. i.e only First letter of each word is CAPITAL.

In [35]:
np.char.title(arr)

array(['Aditya', 'Azad'], dtype='<U6')

In [36]:
np.char.capitalize(arr)

array(['Aditya', 'Azad'], dtype='<U6')

## Numpy - Mathemetical Function

In [37]:
arr1

array([[9, 2, 2, 4],
       [2, 3, 1, 5],
       [1, 5, 4, 3]])

#### sin-usoidal function of each value

In [38]:
np.sin(arr1)

array([[ 0.41211849,  0.90929743,  0.90929743, -0.7568025 ],
       [ 0.90929743,  0.14112001,  0.84147098, -0.95892427],
       [ 0.84147098, -0.95892427, -0.7568025 ,  0.14112001]])

#### cosin function of each value

In [39]:
np.cos(arr1)

array([[-0.91113026, -0.41614684, -0.41614684, -0.65364362],
       [-0.41614684, -0.9899925 ,  0.54030231,  0.28366219],
       [ 0.54030231,  0.28366219, -0.65364362, -0.9899925 ]])

#### tan function of each value

In [40]:
np.tan(arr1)

array([[-0.45231566, -2.18503986, -2.18503986,  1.15782128],
       [-2.18503986, -0.14254654,  1.55740772, -3.38051501],
       [ 1.55740772, -3.38051501,  1.15782128, -0.14254654]])

#### tanh function of each value

In [41]:
np.tanh(arr1)

array([[0.99999997, 0.96402758, 0.96402758, 0.9993293 ],
       [0.96402758, 0.99505475, 0.76159416, 0.9999092 ],
       [0.76159416, 0.9999092 , 0.9993293 , 0.99505475]])

#### log function of each value

In [42]:
np.log10(arr1)

array([[0.95424251, 0.30103   , 0.30103   , 0.60205999],
       [0.30103   , 0.47712125, 0.        , 0.69897   ],
       [0.        , 0.69897   , 0.60205999, 0.47712125]])

#### exponent function of each value

In [43]:
np.exp(arr1)

array([[8.10308393e+03, 7.38905610e+00, 7.38905610e+00, 5.45981500e+01],
       [7.38905610e+00, 2.00855369e+01, 2.71828183e+00, 1.48413159e+02],
       [2.71828183e+00, 1.48413159e+02, 5.45981500e+01, 2.00855369e+01]])

#### square-root function of each value

In [44]:
np.sqrt(arr1)

array([[3.        , 1.41421356, 1.41421356, 2.        ],
       [1.41421356, 1.73205081, 1.        , 2.23606798],
       [1.        , 2.23606798, 2.        , 1.73205081]])

#### power function of each value

In [45]:
np.power(arr1, 2)

array([[81,  4,  4, 16],
       [ 4,  9,  1, 25],
       [ 1, 25, 16,  9]])

#### mean of each value

In [46]:
np.mean(arr1)

3.4166666666666665

#### median of each value

In [47]:
np.median(arr1)

3.0

#### standard deviation of each value

In [48]:
np.std(arr1)

2.1392496088322397

#### variance of each value

In [49]:
np.var(arr1)

4.57638888888889

#### minimum amongst the elements

In [50]:
np.min(arr1)

1

#### maximum amongst the elements

In [51]:
np.max(arr1)

9