## Sort, Search, & Counting functions.

In [26]:
import numpy as np

In [27]:
# array of 10 elements with value ranging from 1-10
arr1 = np.random.randint(1, 10, 10)
arr1


array([4, 9, 6, 2, 5, 9, 2, 8, 1, 5])

In [28]:
np.sort(arr1)

array([1, 2, 2, 4, 5, 5, 6, 8, 9, 9])

#### seearchsorted - Returns the position if a new element is added to the array

In [29]:
np.searchsorted(arr1, 5)

1

#### Count non-zero data values

In [30]:
np.count_nonzero(arr1)

10

#### filter : returns the location of filtered data

In [31]:
np.where(arr1 > 6)


(array([1, 5, 7]),)

#### filter : get the actual data

In [32]:
np.extract(arr1 > 3, arr1)


array([4, 9, 6, 5, 9, 8, 5])

#### Byte Swapping : Displays the data in byte representation

In [33]:
arr1.byteswap()

array([288230376151711744, 648518346341351424, 432345564227567616,
       144115188075855872, 360287970189639680, 648518346341351424,
       144115188075855872, 576460752303423488,  72057594037927936,
       360287970189639680])

#### Deep copy - Copy the data to a different memory location

In [34]:
arr2 = np.copy(arr1)
arr2

array([4, 9, 6, 2, 5, 9, 2, 8, 1, 5])

#### Shallow Copy - a new variable gets the access of the memory location of the data.
- i,e two keys of a lock

In [35]:
arr3 = arr1.view()
arr3

array([4, 9, 6, 2, 5, 9, 2, 8, 1, 5])

In [36]:
arr3[2] = 44

- Value of arr3 changed

In [37]:
arr3

array([ 4,  9, 44,  2,  5,  9,  2,  8,  1,  5])

- Value of arr1 also changed

In [38]:
arr1

array([ 4,  9, 44,  2,  5,  9,  2,  8,  1,  5])

## numpy.matlib : Numpy Matrix Library

In [39]:
import numpy.matlib as nm

#### Matrix with all elements = 0

In [40]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

#### Matrix with all elements = 1

In [41]:
nm.ones((3, 4))


matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### identity matrix

In [42]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Numpy - Linear Algebra

In [43]:
arr4 = np.random.randint([[2,3] , [4,5]])
arr4

array([[0, 1],
       [2, 2]])

In [44]:
arr5 = np.random.randint([[5,3] , [2,5]])
arr5

array([[0, 1],
       [0, 3]])

#### dot product of two matrices

In [45]:
np.dot(arr1, arr2)


565

In [46]:
arr2

array([4, 9, 6, 2, 5, 9, 2, 8, 1, 5])